apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:2yy0mdGk,iv:Hw/54eFRVUaiRtdv6xux+LcHx6564TIIoT9NkYS12l4=,tag:gIBkqcXyS33U73PfaPza5w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:pDOCNg==,iv:gfqK2qhoNNhpissT/yz3kH1nkHKU86L/9YsxSrGzVso=,tag:u0RAkp0aZz05kCwLftMoDA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+vsemYR3FdD/AjC3hoY0iR5rsMnhb+PQAKxGLLNor44nuXkj3DyPRC3QNF4=,iv:FEHt+Z+V1Bs++YHBjNseDp2e4/JYONJLCf+xqGSlrLw=,tag:XPtD3gt3bE4bilzGTPwreA==,type:str]
sops:
    age:
        - recipient: age12jhy43djgv0syqc600uym20jd3xp84vj8sucda03fz96dr08xpps7ftghy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZK29SNnJRY2U0ZFIzNkR2
            SFBDREJaSW1xK21HV3NMeUFFVHpaeFVyc1ZZCmpRRjFOSjhYdXVzcGNpUFBxY1Rk
            dmpEdFdIYlZvMjkzNGR0YVpwUVo5ejQKLS0tIEVqVUE2NEdjOTlyWjVYekJQdUYz
            eG1YYy8zUkpwdnlQS29wVEMxektnNlUKDPwInIkVQVWCjC7ldDQ6vTjsICyutACm
            lfOfXgqpZOxqXBir0zKyMyT47ilMX3ZxBIAhG8jjOg4vZGqBgGeQQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t9hxk98xxze92rxjyq77q79gw7lf6jwa5pn83zqp037qq725z4lsxvqf8x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVmRFYUg0ZmtHQ1NEWU5x
            c0tFbnZNY1JOQXNpdmhLK0xxMUJnU3NQWUNVCkttbHN1d1IyamRBTWdMeCtqUS80
            S0pVd3F0RG1wZmNLdDdHTTBGblg2Q0kKLS0tIE94YW8vQVoxbEUwQVRjN3ZsdUgz
            eGphK0syZUMwU09SY1M3T2d1VkwyZHMKxTsUNxxsqm7n7yYJ1sOyg560FTZzk2If
            svoLt3aqQuGmqK2ESnmKDJF1mts7V7xduiHkJJXzJc57ha17YZpRCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-27T07:55:19Z"
    mac: ENC[AES256_GCM,data:CZbhFOMm1VncygIufc57llC4SSEwxDrUwhfkSh9ppvDvyAiDfjK75vmRHCuCp2GvsV5sSRfDUdh6HpUhe5sMCQ9tNPlxhDywfayCZOURvxYlP7enjQ6OrJurx9u5+uM2lyjXLXKwB//xLlDU72pUA8eORtdoydSkOIgBya7kZeU=,iv:kdr44MOOUEN43KQaDcXJ2DD3sWBDE/B1IclUbLbGzjM=,tag:XZzTBtkNtdSwHrsBjJjbXQ==,type:str]
    pgp:
        - created_at: "2026-09-27T07:55:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA13affh08wENAQv/fB4n3C69iG93ZZmLIXBsd9eOt27Kl8Aj/m3AUDjPmjiS
            IwU+pq7bLBFkR0Q5hLeSJQsbdeosdRbYfVEfzxZF1tXJ+x8YjCz5e1hQbZxu+tRD
            f091x+1MxIquN++keMadZcveE/qymDAXUfzL1pGo6uaAgda+ly1UzLme0PLjMQgR
            j3s32l/BRGGuzQaqudr4FhyRxyLQkiUELh/LlWfRQYIowmBsC/1GgQhOE1yPFWYZ
            dOOj02ZCq0t/AV/D1hBxnrcom8dKfkbEPM9CmPlB6JaiHsyfxsDwloa9liBZyXa3
            nURB0asoNXaEpQ3jbDbTsZnfUgTMTss/ohG/UEuX6781ymulqor6Vs7tKK9L1pfe
            nT6z8z/V0Xkx7I04yKl8Yn9LHcbAxCEE0RgeW4PVs1F3HRYdFglkBFVu89oZYR5v
            dip+2GJBtWXWTdMGdjSQ2TBnyIeS6iyG05iMryNl11c+F2xAKZeRGrK4Kq2BPo43
            7iXS0tJmLaSLesJpvUq81GgBCQIQ1U8Q9dFxyuwt5Acs6WkDFEmTiIVaXYv1wIcY
            PFELtB5GSi+oTL2aJsaF0bcZPA0zsKPqqYzW9xHR6K5hOpAEqwUEZtglD2DHxo2D
            s80XTHd+2ODh21MwXlVmynd+suT02xfjow==
            =aIVj
            -----END PGP MESSAGE-----
          fp: C4F8BFBD82E39F4C89669C443B3CC85CF5833E90
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
