apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grad
resources:
  - spaceship-api.sops.yaml
  - network-policy.yaml
  - cronjob.yaml
configMapGenerator:
  - name: ddns-script
    files:
      - update.sh
