apiVersion: v1
data:
    ADMIN_SESSION_SECRET: ENC[AES256_GCM,data:kmkYz2nZkwbm4xAv4C0g46r7oLM=,iv:8YzUYgxuEzHu/F57KqqCNVxKJFSV5yHP3TGtmXqPdZ0=,tag:Ir4XdwaI6qgsZuHbbm7Rgw==,type:str]
    PASS_SIGNING_KEY: ENC[AES256_GCM,data:ksfB/D6y9E2GOdGFEd/dLz4GoDX/8/bIbxrKK/MKq2fZZoKMqMT+BUxGGgX6ZcQ/8q5C99Gd5OjAuL6ZgTLchqt40w9qKfhp0kzm1QN6Xxc2tpTzO6dG2mV3WHMIcPHSHrRj+Pm5yVCQsFWfdCuLNl0REiIeVDkEes53vB8+XePyxwgfugU0XlE3Lmn7ycBHIVhSVvaZy+KwFNvH3uulBw==,iv:HGHYAeQoS3dTTcVhycn2u5jSvqBuThXrcNpEDFOIvNg=,tag:k/cbQZanuDpYCfjvIFhuMA==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZH1BFjAIPGk96GNrCJ+v/HCtoqUe6pWsxSIa6w==,iv:ewrkhTte40DokJB2Q5+IBHGrs/QTWB19UUXgnzPnIxo=,tag:YGlzUlXjy0K/gxnY4/sbOQ==,type:str]
    S3_BUCKET_DERIVATIVES: ENC[AES256_GCM,data:1cH8+4LN8ja8aCPDG2XJ9ATnRap3+wkc,iv:3kEcHB5MscPq3j8bumt1RP5p+vQmfwGx/HgqZaAlnHY=,tag:4XFD4Bnw9vkc+GHhZzfegw==,type:str]
    S3_BUCKET_ORIGINALS: ENC[AES256_GCM,data:2rMl267Yls1wVIHZmRV5xhRyFfs=,iv:xout4M4tzmqgaVbMgl7m+cCfET1LTXwXct4R3Dwk4fk=,tag:FHvn5MqlxoDnxdYPKINn4w==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:URIPJ9hVt0Z8Ve2kd32Z6Fb9fkfvIUZZVzgR98lJstfe/TGs,iv:JdWio1/6tQKcZ0T4GURynjF0AVLpw6vhbQDl0fscSw0=,tag:bsC5ihYYm1lRKGw/N9p9Fg==,type:str]
    S3_REGION: ENC[AES256_GCM,data:K1aiMKniuXI=,iv:LXUkgfZhIJF6EcoaPUzQ/UQ0zhTft1iEYHoY8sGGVPU=,tag:WcYLClJ1ta4VLm+03Cppdg==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tVh430lWfim6F0uxD2V8y68Wg4zPKLOaAM7xIQ==,iv:VEgQXtcKGQ4hAG0ZaIaNQMY8SRKw1S8kQY9l2aMc6pw=,tag:KhGp6ZcsCKoTCB5qG/Xa5A==,type:str]
    SERVICE_TOKEN_PRINTER: ENC[AES256_GCM,data:kLHnAtzoxC3ufQlFFvcBplCaL/3xMOQ4VhoXz1NWRhDzOQAnIbfTl72j33pGClIQ7QTBKFIuk4r8xHuU1vutx4347w1zcgRfIVMtTkZ9ghwYeilAIw7QNg==,iv:fc2TPn4u2/BXD5i0pAifZhqK54PDcLZrKEnCQ+0sBwg=,tag:6KGrOsLARqZkrGguJKCeMw==,type:str]
    SERVICE_TOKEN_TRANSLATION: ENC[AES256_GCM,data:HOFyc6LwvMh/SDmHONQuMBn20qMwtCF5BNGl5AO4Q79be1qSTkNwiZvlfgVK3H22Ej5uLIzfk82dKoSbE4+o2pqOPeRHXpAnwAulOT6tNJIKM5Mp/Ezx6A==,iv:KRFVb24g9iyh5lCGcKQHzPrjA3Yal6c38+L/uVMsYwc=,tag:L95zBlc90nkwq0l9F4xiSw==,type:str]
kind: Secret
metadata:
    name: api-secrets
    namespace: grad
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Zll4cXZSVkVWQkRLaDlO
            RzNmam9laHNpRUoxQi9aODJaaXloRHhtOEY4CkNsSlFtVWNkbUlRWEU0dFFzZUQz
            WG4xVWFRT0ZEbDh6VEpvY0V2N09pWUUKLS0tIFpaV3lCdVdkVlZ5akNkMHBOWFQr
            NTV0cStoNmJqdjV0OEhRWnBZYVkzWXcKs8B9VsyGbIVgj+j3P24xoz4zyyAmyvnN
            r3lGBUZD4qB1iS4KfPHS7GItuhjoVEvDT+pukQ1IbtX80kDbKHMdzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12jhy43djgv0syqc600uym20jd3xp84vj8sucda03fz96dr08xpps7ftghy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLb2dpUVpDUTZWMDNYNEli
            cTVVZnc5VTJveGxtdGdWSy9XWDAxeHFmcTFZCkR2bzltWXlESVJ0SFBSMDRuZjlM
            bWh1b3pDcmpmS1V6OGpmYk1jRXdIdk0KLS0tIFdNOXp6MWtWRTM4SVpFdjVGdkRU
            MldBbkFxWFl6a0JvVWtrejdBdVlYWE0KQMQlaygheeg6R/ufMXqvBFVUWtxXWk2Q
            WnILSK6q0vMJ2zC3i+DVMjkWeo6urfvkArGBl2EMFIJzYN0aewnOLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t9hxk98xxze92rxjyq77q79gw7lf6jwa5pn83zqp037qq725z4lsxvqf8x
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T16:53:05Z"
    mac: ENC[AES256_GCM,data:mk+IwcF5gt4G+TbZ1raTLpCXk5U/Sa7RNlh1qJiTcDNnWci8DUCrsmSMAgmhDmTkACQkHsXa001mi2hJtJ67zu40rlGJ7Fy/Uf/KQmyxYRQhfRZZpeJGrEJ0/XcBi9HJhnYIm9jUsbcfUtzxJT0FHrJfbJH6kcHuim+RVavB13U=,iv:4mFOJz4kbtyY8gAwtdVGi7ZKwCNs58jPr5OOEiOuI+M=,tag:rOUIP5HWYQOTWTvuHQW2Rw==,type:str]
    pgp:
        - created_at: "2026-09-29T16:53:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA13affh08wENAQwAvxV2Fv+iCrI3SI54l1w3ycdzjI6LWi8vJv5bfY5BO6bh
            08Z/jg0EHCr5i0q9e+4lxu2fS9G+lOD5BvJl2xcVI9EunJtamD1BPZU54qgJ8Kn6
            5gTzxAoX1EfgiFTtxk7zgLCB6H0ODqpNa1pF6v5dTP4bwwoZ6nf6gNkpVXncv0tO
            YLxv2xzVLEk1CqLDNa7m7I7O7i/hKROI+Ycs3XiZ4auRPM5mq1PL1Qf2pE5F/uMb
            2cfjjGkij+89c+6fMk47JYh8rZVp5+pZop4V217CjGDxoGaaR7VuJkl/BNSQ3Kgu
            QruLO67dPBDhHmekTsSf6UPt8Kz+yjm26ipl+SMi4X569Q2IqJrVjTYyflnCD13p
            XhCV+G+C6G1FiKudDIL49+ElRJoWVkSSV2dkdgleoGqA2EJNnmNLSmV5v+FiZPJc
            /ycOTCth8cGwogL5ltyvYog0TJ4SRUkTSZMUO0YGWa9iOqjMs24KwJ1b4fCQ0lY8
            HGI3q8yLR2iGbuSFJby51GgBCQIQ87FbdvdrUAoYZU6hukh1e5SPGorC21SOuKAp
            h7IIJ0JPm7T7JA08kGbAQcvII1qy03QNxVT02HVdlv/QSY0gcrWkXs/PM6vugrg/
            6C040RsAV9QQzFHnqwJ7Bn2nNTfGEmDZ+A==
            =iu71
            -----END PGP MESSAGE-----
          fp: C4F8BFBD82E39F4C89669C443B3CC85CF5833E90
    version: 3.13.3
